In [16]:
import numpy as np
from copy import copy
import random

In [17]:
def initialize_population( num_individuals, num_variables ):
    """
    Khởi tạo quần thể gồm num_individuals cá thể. Mỗi cá thể có num_parameters biến.
    
    Arguments:
    num_individuals -- Số lượng cá thể
    num_variables -- Số lượng biến
    
    Returns:
    pop -- Ma trận (num_individuals, num_variables ) chứa quần thể mới được khởi tạo ngẫu nhiên.
    """
    
    ### BẮT ĐẦU CODE TỪ ĐÂY ### 
    pop = np.random.randint(2, size=(num_individuals, num_variables))
    
    ### DỪNG CODE TẠI ĐÂY ###
    
    return pop

In [18]:
def onemax( ind ):
    """
    Hàm đánh giá OneMax: Đếm số bit 1 trong chuỗi nhị phân (cá thể ind).
    
    Arguments:
    ind -- Cá thể cần được đánh giá.

    Returns:
    value -- Giá trị của cá thể ind.
    """
    
    ### BẮT ĐẦU CODE TỪ ĐÂY ###     
    value = np.sum(ind)
    
    ### DỪNG CODE TẠI ĐÂY ###
    
    return value

In [19]:
def compare_fitness(fitness_1, fitness_2, maximization=True):
    if maximization:
        if fitness_1 > fitness_2:
            return True
    else:
        if fitness_1 < fitness_2:
            return True
        
    return False

In [24]:
def tournament_selection( pop, pop_fitness, selection_size, tournament_size=4):
    """
    Hàm chọn lọc cạnh tranh.
    
    Arguments:
    pop -- Quần thể để thực hiện phép chọn lọc.
    pop_fitness -- Mảng 1 chiều chứa giá trị (độ thích nghi) của từng cá thể trong quần thể.
    selection_size -- Số lượng cá thể sẽ được chọn.
    tournament_size -- Kích thước của tournament: Số lượng các cá thể được so sánh với nhau mỗi lần.
    
    Returns:
    selected_indices -- Chỉ số của những cá thể trong quần thể pop được chọn. Chỉ số có thể được lặp lại.
    """
    
    num_individuals = len(pop) # lấy ra số lượng cá thể
    indices = np.arange(num_individuals) # khai báo mảng indices để lấy chỉ số của từng các cá thể
    selected_indices = [] # danh sách chứa các chỉ số của các cá thể được lựa chọn
    
    while len(selected_indices) < selection_size:
        # Đảo ngẫu nhiên thứ tự các cá thể trong quần thể.
        np.random.shuffle(indices)
        
        for i in range(0, num_individuals, tournament_size): # quét qua số lượng cá thể trong quần thể và chia thành từng bảng đấu
            best_idx = i # cá thể tốt nhất
            for idx in range(1, tournament_size): # cho các cá thể trong bảng đấu với nhau, và chọn đứa có độ thích nghi tốt hơn
                if compare_fitness(pop_fitness[indices[i+idx]], pop_fitness[indices[best_idx]]):
                    best_idx = i+idx
            selected_indices.append(indices[best_idx])

    selected_indices = np.array(selected_indices)
        
    return selected_indices

In [21]:
def crossover( pop ):
    """
    Hàm biến đổi tạo ra các cá thể con.
    
    Arguments:
    pop -- Quàn thể hiện tại.

    Returns:
    offspring -- Quần thể chứa các cá thể con được sinh ra.
    """  
    
    ### BẮT ĐẦU CODE TỪ ĐÂY ### 
    num_individuals = len(pop)
    num_parameters = len(pop[0])
    indices = np.arange(num_individuals)
    # Đảo ngẫu nhiên thứ tự các cá thể trong quần thể
    np.random.shuffle(indices)
    offspring = []
    
    for i in range(0, num_individuals, 2):
        idx1 = indices[i]
        idx2 = indices[i+1]
        offspring1 = list(pop[idx1])
        offspring2 = list(pop[idx2])
        
        # Cài đặt phép lai đồng nhất uniform crossover. 
        # Không cần cài đặt đột biến mutation.
        for idx in range(0, num_parameters):
            r = np.random.rand()
            if r < 0.5:
                temp = offspring2[idx] 
                offspring2[idx] = offspring1[idx]
                offspring1[idx] = temp

        offspring.append(offspring1)
        offspring.append(offspring2)


    ### DỪNG CODE TẠI ĐÂY ###
    
    offspring = np.array(offspring)
    return offspring

In [22]:
def genetic_algorithm(num_individuals, num_parameters, num_generations):
    pop = initialize_population(num_individuals, num_parameters)
    pop_fitness = np.array([onemax(ind) for ind in pop])
    print("#Gen 0:")
    print(pop_fitness)

    selection_size = num_individuals #do default tournament size = 4

    for i in range(num_generations):
        #Tạo quần thể con
        offspring = crossover(pop)
        offspring_fitness = np.array([onemax(ind) for ind in offspring])

        #Trộn quần thể hiện tại và quần thể con
        pool = np.vstack([pop, offspring])
        pool_fitness = np.concatenate((pop_fitness, offspring_fitness))

        #Tournament selection trên quần thể mới trộn
        selected_indices = tournament_selection( pool, pool_fitness, selection_size )
        pop = pool[selected_indices,:]
        pop_fitness = pool_fitness[selected_indices]

        print(f'#Gen {i+1}:')
        print(pop_fitness)
    
    print('#Final result:')
    print(pop)
    print(pop_fitness)


In [39]:
# Trường hợp kích thước quần thể là 10, số biến là 8
np.random.seed(19522274)
num_parameters = 8 # số biến
num_individuals = 10
num_generations = 10
genetic_algorithm(num_individuals, num_parameters, num_generations)

#Gen 0:
[3 3 1 3 6 5 6 5 4 4]
#Gen 1:
[6 5 4 5 7 6 5 5 5 7]
#Gen 2:
[8 6 6 6 7 8 6 5 6 7]
#Gen 3:
[8 8 8 7 7 8 8 6 8 8]
#Gen 4:
[8 8 8 8 8 8 8 8 8 8]
#Gen 5:
[8 8 8 8 8 8 8 8 8 8]
#Gen 6:
[8 8 8 8 8 8 8 8 8 8]
#Gen 7:
[8 8 8 8 8 8 8 8 8 8]
#Gen 8:
[8 8 8 8 8 8 8 8 8 8]
#Gen 9:
[8 8 8 8 8 8 8 8 8 8]
#Gen 10:
[8 8 8 8 8 8 8 8 8 8]
#Final result:
[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]
[8 8 8 8 8 8 8 8 8 8]


* Nhận xét: Với  prob_size = 8 và pop_size = 10 thì quần thể đạt hội tụ về 1 và tìm được cá thể tốt nhất là [1 1 1 1 1 1 1 1]

In [44]:
# Trường hợp kích thước quần thể là 16, số biến là 16
np.random.seed(19522274)
num_parameters = 16 # số biến
num_individuals = 16
num_generations = 10
genetic_algorithm(num_individuals, num_parameters, num_generations)

#Gen 0:
[ 6  4 11 11  8  7 10  8  3  4  5  6  8 12  5  7]
#Gen 1:
[11  9 12 10  8  7  8 12 12 12  9  8  7 11 11 10]
#Gen 2:
[11 11 12 12 13 12 11 11 11 12 11 11 12 13 10 12]
#Gen 3:
[13 11 12 12 12 13 13 13 13 13 12 12 13 12 13 12]
#Gen 4:
[13 13 13 13 13 14 13 13 13 13 13 13 13 13 13 14]
#Gen 5:
[13 13 13 14 15 13 14 14 13 15 14 14 13 14 14 13]
#Gen 6:
[14 15 14 15 15 14 14 14 14 15 15 14 14 15 15 14]
#Gen 7:
[16 15 16 15 15 15 15 16 14 16 15 16 15 16 16 15]
#Gen 8:
[16 16 15 16 16 16 16 16 16 16 16 16 16 16 16 16]
#Gen 9:
[16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16]
#Gen 10:
[16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16]
#Final result:
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1

In [53]:
# Trường hợp kích thước quần thể là 30, số biến là 32
np.random.seed(19522274)
num_parameters = 32 # số biến
num_individuals = 30
num_generations = 10
genetic_algorithm(num_individuals, num_parameters, num_generations)

#Gen 0:
[10 22 15 18  7 11 20 12 15 17 17 16 15 19 13 15 18 15 19 14 15 12 16 12
 20 14 20 22 16 15]
#Gen 1:
[17 22 22 20 20 20 20 20 19 16 15 22 18 18 22 18 22 22 17 20 22 18 14 20
 16 20 19 22 20 20]
#Gen 2:
[22 20 20 22 22 20 22 21 20 22 18 22 25 24 23 24 25 20 22 22 24 20 22 20
 23 23 22 20 22 22]
#Gen 3:
[25 25 25 26 24 26 22 23 23 23 22 23 23 22 23 24 26 23 23 25 26 22 23 21
 23 25 24 22 25 23]
#Gen 4:
[25 25 26 26 25 26 25 23 26 25 24 25 26 28 25 24 25 25 24 24 28 25 26 26
 26 25 26 26 25 23]
#Gen 5:
[27 26 26 26 26 28 27 29 28 26 26 26 27 26 26 27 27 27 26 28 26 27 26 26
 26 29 28 26 26 26]
#Gen 6:
[28 27 29 29 26 27 28 28 30 30 28 28 28 28 27 29 28 29 26 27 29 27 28 28
 28 28 28 30 30 27]
#Gen 7:
[28 30 29 30 29 28 30 29 30 29 29 30 30 30 28 29 29 29 29 30 30 29 29 30
 29 28 30 30 30 29]
#Gen 8:
[30 30 30 29 30 30 29 32 30 30 30 30 30 30 30 30 30 30 29 30 32 30 30 29
 30 30 30 30 30 30]
#Gen 9:
[30 31 30 30 30 31 32 32 32 31 30 30 32 30 30 31 32 30 30 32 30 31 30 30
 32 31 30 

In [68]:
# Trường hợp kích thước quần thể là 60, số biến là 64
np.random.seed(19522274)
num_parameters = 64 # số biến
num_individuals = 60
num_generations = 20
genetic_algorithm(num_individuals, num_parameters, num_generations)

#Gen 0:
[32 33 18 32 32 33 34 28 33 33 27 28 34 42 31 40 40 34 38 25 39 28 27 31
 41 35 33 31 31 26 37 32 39 29 32 32 28 25 36 38 31 35 23 35 33 26 29 25
 34 29 31 27 32 35 35 25 30 34 30 33]
#Gen 1:
[35 37 38 40 39 35 39 40 32 31 33 35 34 38 41 37 37 33 35 37 42 31 33 33
 33 38 31 40 37 38 33 34 38 39 31 33 33 39 32 32 33 31 31 35 38 36 38 37
 40 38 37 35 34 41 40 36 33 37 42 33]
#Gen 2:
[43 46 35 40 37 41 37 36 40 41 38 40 35 38 41 40 42 39 39 38 41 39 37 37
 39 44 40 38 41 42 41 33 40 37 44 40 40 40 38 41 42 41 38 38 36 39 38 39
 39 41 40 46 38 40 38 39 40 42 43 38]
#Gen 3:
[45 42 40 40 42 46 44 41 40 44 41 42 41 44 46 39 43 42 41 41 43 45 41 41
 44 42 43 40 44 44 44 43 39 45 45 41 42 42 46 41 44 43 45 40 40 44 40 44
 44 41 42 40 41 44 42 43 43 42 46 41]
#Gen 4:
[45 46 44 44 43 43 44 42 46 42 43 47 47 43 45 43 48 45 44 43 45 48 46 46
 47 43 45 43 44 50 45 44 47 43 44 45 44 44 44 48 45 44 45 44 44 44 47 42
 45 48 45 44 45 46 43 50 46 43 46 46]
#Gen 5:
[47 49 49 48 54 49 50 46 51 44 4

* Nhận xét: Khi tăng prob_size = 64 thì thực nghiệm với pop_size trong khoảng [32;64] quần thể không đạt hội tụ vì vậy phải tăng số thế hệ lên 20 thì quần thể đạt hội tụ và cho được kết quả tốt nhất.